<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'XIVAPI\\' => array($vendorDir . '/xivapi/xivapi-php/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
);
